### ISSUE TITLE
feature request: support a null to_relationship

### ISSUE THREAD

**Issue by karenetheridge** [kentnl/Dist-Zilla-Plugin-Prereqs-Soften#3]
```
[Prereqs::Soften]
to_relationship =
copy_to = develop.requires
```

...would allow moving a prereq from runtime.requires or test.requires to develop.requires, without adding another runtime/test entry (e.g. for optional features or for tests that use Test::Requires).

**Comment by kentfredric** [comment]
I think this is why many of my other prereq modules have a raw " a -> b" translation map under the hood.

Turns out we only think YAGNI and then we end up NIL :p

**Comment by kentfredric** [comment]
I believe this was fixed in https://metacpan.org/release/KENTNL/Dist-Zilla-Plugin-Prereqs-Soften-0.006000 in b8766bcb7381d5681e3716cab78900fd7c6353a4 with 
```ini
   to_relationship = none
```
