### ISSUE TITLE
`copy_to` not always validated

### ISSUE THREAD

**Issue by karenetheridge** [kentnl/Dist-Zilla-Plugin-Prereqs-Soften#4]
I had this config for a while, which was silently doing nothing (on the copy side):

```
[Prereqs::Soften]
:version = 0.006000
module = Dist::Zilla::Plugin::OurPkgVersion
copy_to = develop
to_relationship = none
```

That `copy_to` apparently needs to be `develop.requires`.  Note that `develop.foo` throws an error, but `develop` is silently accepted and does nothing - it's as if no copy_to was specified at all.

Would it be possible to validate the `copy_to` field and barf if it is not correct?

**Comment by kentfredric** [comment]
Bah. I never get the github close messages right.

**Comment by karenetheridge** [comment]
w00t, many thanks!
